on: [push]
  # push:
    # paths:
      # - 'aws-sam/**'
defaults:
  run:
    working-directory: aws-sam
jobs:
  pytest:
    runs-on: ubuntu-latest
    environment: aws-sam
    permissions:
      id-token: write
      contents: read
    steps:
    # https://stackoverflow.com/questions/64405836/github-actions-no-such-file-or-directory-on-any-run-step
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - run: |
        pip install pytest
        pytest
  sam-build-deploy:
    needs: pytest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    # https://github.com/aws-actions/setup-sam
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: sam validate
    - run: sam build
    # Prevent prompts and failure when the stack is unchanged
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset 