on: [push]
  # push:
    # paths:
      # - 'aws-sam/**'
defaults:
  run:
    working-directory: aws-sam
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    # https://stackoverflow.com/questions/64405836/github-actions-no-such-file-or-directory-on-any-run-step
    - uses: actions/checkout@v3
    - run: pytest
  sam-build-deploy:
    needs: pytest
    runs-on: ubuntu-latest
    # https://github.com/aws-actions/setup-sam
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run: sam validate
    - run: sam build
    # Prevent prompts and failure when the stack is unchanged
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset 